### ISSUE TITLE
Version of pg module is outdated

### ISSUE THREAD

**Issue by martbrugg** [krisdaniels/node-red-contrib#2]
Hi! 
With the latest version i have problems to establish a connection to my cloudbased pg-database.
When i update the version of the pg-module to the latest version it works. 
Is it possible to update the package.json to the lates pg module (6.1.0)

**Comment by akobelan** [comment]
Can you describe your "problems" in more detail? I may be experiencing the same thing.

**Comment by akobelan** [comment]
I second this suggestion. Here are the dependancies:

    "pg": "6.1.2",
    "node-postgres-named": "2.4.1",
    "querystring": "0.2.0"

And now my flaky postgresql connections stop getting randomly rejected reporting incorrect passwords.

**Comment by siscia** [comment]
:+1: 

I got the same problem, how did you solve?
@akobelan

**Comment by sn0wcat** [comment]
After updating the outdated dependencies , the problem with randomly reporting incorrect passwords is gone. I will submit a pull request fixing this.

**Comment by sn0wcat** [comment]
Pull Request submitted, but this repository seems to be abandoned....

**Comment by krisdaniels** [comment]
just a little bit abandoned ;)  didn't notice the initial message, however the pull req is merged into master and i will update the npm package later this week
Thanks for the modifications

**Comment by krisdaniels** [comment]
package is published v0.6.1
https://www.npmjs.com/package/node-red-contrib-postgres
