### ISSUE TITLE
Unable to setup authentication

### ISSUE THREAD

**Issue by ItsmeJulian** [krisdaniels/node-red-contrib#4]
I use node-red v0.16.2 on debian8 x64 and cannot connect to the database, also I setup the database and imported the flow from the README.md. 
```
user@debian:~$ psql postgres
psql (9.6.3)
Type "help" for help.

postgres=# \d+
                    List of relations
 Schema |  Name  | Type  |  Owner   | Size  | Description 
--------+--------+-------+----------+-------+-------------
 public | table1 | table | postgres | 16 kB | 
(1 row)

postgres=# SELECT * FROM table1;
postgres-#  <<< I AM SUPERUSER on this database
 field1 | field2 
--------+--------
 row1   |      1
 row2   |      2
(2 rows)
```
In edit postgres node I have localhost:5432/postgres with database postgres.
For username/password i tried various combinations:
- leaving both empty
- user/empty
- user/mydebianpw for user profile 

The console says for both fields empty:
> msg : error
> "error: password authentication failed for user "user""

I am running out of options here, what to do?

**Comment by krisdaniels** [comment]
did you setup a postgress password ? you need to create a postgress user and configure it in node-red
